### ISSUE TITLE
credssp: Server did not response with a CredSSP token after step Step 1. TLS Handshake

### ISSUE THREAD

**Issue by sf32738** [jborean93/requests-credssp#18] opened 2020-08-05 11:44 UTC
## Error
```
$ ansible -i inventory/devops -m setup devops-winsvr2012-01 -vvvvvv
ansible 2.9.11
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/library', '/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
Using /home/ansible/.ansible.cfg as config file
Reading vault password file: /home/ansible/.vault-password
setting up inventory plugins
host_list declined parsing /home/ansible/inventory/devops as it did not pass its verify_file() method
script declined parsing /home/ansible/inventory/devops as it did not pass its verify_file() method
auto declined parsing /home/ansible/inventory/devops as it did not pass its verify_file() method
Parsed /home/ansible/inventory/devops inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/lib/python3.8/dist-packages/ansible/plugins/callback/minimal.py
META: ran handlers
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/windows/setup.ps1
Pipelining is enabled.
<10.10.190.109> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO 10.10.190.109
<10.10.190.109> WINRM CONNECT: transport=credssp endpoint=https://10.10.190.109:5986/wsman
<10.10.190.109> WINRM CONNECTION ERROR: Server did not response with a CredSSP token after step Step 1. TLS Handshake - actual 'Negotiate, CredSSP'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/connection/winrm.py", line 413, in _winrm_connect
    self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
  File "/home/ansible/.local/lib/python3.8/site-packages/winrm/protocol.py", line 166, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/home/ansible/.local/lib/python3.8/site-packages/winrm/protocol.py", line 243, in send_message
    resp = self.transport.send_message(message)
  File "/home/ansible/.local/lib/python3.8/site-packages/winrm/transport.py", line 323, in send_message
    response = self._send_message_request(prepared_request, message)
  File "/home/ansible/.local/lib/python3.8/site-packages/winrm/transport.py", line 328, in _send_message_request
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/home/ansible/.local/lib/python3.8/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/ansible/.local/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/ansible/.local/lib/python3.8/site-packages/requests_credssp/credssp.py", line 448, in response_hook
    response = self.handle_401(response, **kwargs)
  File "/home/ansible/.local/lib/python3.8/site-packages/requests_credssp/credssp.py", line 483, in handle_401
    in_token = self._get_credssp_token(response, credssp_regex,
  File "/home/ansible/.local/lib/python3.8/site-packages/requests_credssp/credssp.py", line 517, in _get_credssp_token
    raise AuthenticationException(error_msg)
requests_credssp.exceptions.AuthenticationException: Server did not response with a CredSSP token after step Step 1. TLS Handshake - actual 'Negotiate, CredSSP'
devops-winsvr2012-01 | UNREACHABLE! => {
    "changed": false,
    "msg": "credssp: Server did not response with a CredSSP token after step Step 1. TLS Handshake - actual 'Negotiate, CredSSP'",
    "unreachable": true
}
```

## Ansible Inventory Settings
```
[windows:vars]
ansible_user=<redacted>
ansible_password=<redacted>
ansible_connection=winrm
ansible_winrm_transport=credssp
ansible_winrm_server_cert_validation=ignore

[windows]
devops-winsvr2012-01   ansible_host=10.10.190.109
```

## Ansible Environment

$ cat /etc/lsb-release 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

$ ansible --version
```
ansible 2.9.11
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/library', '/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

$ pip3 list | egrep  "winrm|credssp"
```
pywinrm                0.4.1               
requests-credssp       1.1.1               
winrmlib               1.3  
```

## Remote (from Ansible) CURL to Windows Server 2012R2
```

$ curl -kvvv https://10.10.190.109:5986/wsman
--
*   Trying 10.10.190.109:5986...
* TCP_NODELAY set
* Connected to 10.10.190.109 (10.10.190.109) port 5986 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=WIN-U5410N2J187
*  start date: Aug  3 17:07:52 2020 GMT
*  expire date: Aug  1 17:07:52 2030 GMT
*  issuer: CN=Atlantic.Net Management - Do not remove
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /wsman HTTP/1.1
> Host: 10.10.190.109:5986
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 405
< Allow: POST
< Server: Microsoft-HTTPAPI/2.0
< Date: Wed, 05 Aug 2020 11:33:17 GMT
< Connection: close
< Content-Length: 0
<
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
```

## Windows Environment
Operating System: Windows Server 2012R2
SSL Certificate: Self Signed

WinRM / CredSSP setup was done via the Ansible provided PowerShell script, same on all Windows Servers tested against.
https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

```

PS C:\Users\Administrator> Test-WSMan
--
 
 
wsmid           : http://schemas.dmtf.org/wbem/wsman/identity/1/wsmanidentity.xsd
ProtocolVersion : http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd
ProductVendor   : Microsoft Corporation
ProductVersion  : OS: 0.0.0 SP: 0.0 Stack: 3.0
 
 
 
PS C:\Users\Administrator> winrm e winrm/config/listener
Listener
Address = *
Transport = HTTP
Port = 5985
Hostname
Enabled = true
URLPrefix = wsman
CertificateThumbprint
ListeningOn = 10.10.190.109, 127.0.0.1, ::1, fe80::5efe:10.10.190.109%14, fe80::14e4:a20e:167f:f4e0%12
 
Listener
Address = *
Transport = HTTPS
Port = 5986
Hostname = WIN-U5410N2J187
Enabled = true
URLPrefix = wsman
CertificateThumbprint = A0CF12605DBBD41E4B3591A6B092D81B4504ED6B
ListeningOn = 10.10.190.109, 127.0.0.1, ::1, fe80::5efe:10.10.190.109%14, fe80::14e4:a20e:167f:f4e0%12
 
 
 
PS C:\Users\Administrator> winrm get winrm/config
Config
MaxEnvelopeSizekb = 500
MaxTimeoutms = 60000
MaxBatchItems = 32000
MaxProviderRequests = 4294967295
Client
NetworkDelayms = 5000
URLPrefix = wsman
AllowUnencrypted = false
Auth
Basic = true
Digest = true
Kerberos = true
Negotiate = true
Certificate = true
CredSSP = true
DefaultPorts
HTTP = 5985
HTTPS = 5986
TrustedHosts
Service
RootSDDL = O:NSG:BAD:P(A;;GA;;;BA)(A;;GR;;;IU)S:P(AU;FA;GA;;;WD)(AU;SA;GXGW;;;WD)
MaxConcurrentOperations = 4294967295
MaxConcurrentOperationsPerUser = 1500
EnumerationTimeoutms = 240000
MaxConnections = 300
MaxPacketRetrievalTimeSeconds = 120
AllowUnencrypted = false
Auth
Basic = false
Kerberos = true
Negotiate = true
Certificate = false
CredSSP = true
CbtHardeningLevel = Relaxed
DefaultPorts
HTTP = 5985
HTTPS = 5986
IPv4Filter = *
IPv6Filter = *
EnableCompatibilityHttpListener = false
EnableCompatibilityHttpsListener = false
CertificateThumbprint
AllowRemoteAccess = true
Winrs
AllowRemoteShellAccess = true
IdleTimeout = 7200000
MaxConcurrentUsers = 10
MaxShellRunTime = 2147483647
MaxProcessesPerShell = 25
MaxMemoryPerShellMB = 1024
MaxShellsPerUser = 30
```

## Windows Event Log Errors
```
Log Name:      System
Source:        Schannel
Date:          8/5/2020 5:16:37 AM
Event ID:      36888
Task Category: None
Level:         Error
Keywords:      
User:          SYSTEM
Computer:      WIN-U5410N2J187
Description:
A fatal alert was generated and sent to the remote endpoint. This may result in termination of the connection. The TLS protocol defined fatal error code is 40. The Windows SChannel error state is 1205.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Schannel" Guid="{1F678132-5938-4686-9FDC-C8FF68F15C85}" />
    <EventID>36888</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2020-08-05T12:16:37.933329200Z" />
    <EventRecordID>2708</EventRecordID>
    <Correlation />
    <Execution ProcessID="520" ThreadID="2864" />
    <Channel>System</Channel>
    <Computer>WIN-U5410N2J187</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="AlertDesc">40</Data>
    <Data Name="ErrorState">1205</Data>
  </EventData>
</Event>



Log Name:      System
Source:        Schannel
Date:          8/5/2020 5:16:37 AM
Event ID:      36874
Task Category: None
Level:         Error
Keywords:      
User:          SYSTEM
Computer:      WIN-U5410N2J187
Description:
An TLS 1.2 connection request was received from a remote client application, but none of the cipher suites supported by the client application are supported by the server. The SSL connection request has failed.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Schannel" Guid="{1F678132-5938-4686-9FDC-C8FF68F15C85}" />
    <EventID>36874</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2020-08-05T12:16:37.933329200Z" />
    <EventRecordID>2707</EventRecordID>
    <Correlation />
    <Execution ProcessID="520" ThreadID="2864" />
    <Channel>System</Channel>
    <Computer>WIN-U5410N2J187</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="Protocol">TLS 1.2</Data>
  </EventData>
</Event>
```

----
CredSSP is working against my Windows Server 2016 and Windows Server 2019 test servers.  However, when I started testing against Windows Server 2012R2, I get these failures.

Can anyone provide some thoughts or point me in a direction to further troubleshoot ?

**Comment by sf32738** [comment] 2020-08-05 11:51
Attached is a PCAP of the traffic leaving the ansible server, going to the Windows Server 2012R2 machine.
[credssp_error.zip](https://github.com/jborean93/requests-credssp/files/5028094/credssp_error.zip)

**Comment by sf32738** [comment] 2020-08-05 12:29
Attached is a list of SCHANNEL settings that I have enabled on the server.
[SecuirtyProviders_SCHANNEL.txt](https://github.com/jborean93/requests-credssp/files/5028354/SecuirtyProviders_SCHANNEL.txt)

**Comment by jborean93** [comment] 2020-08-05 19:37
Unfortunately the PCAP isn't very useful because the connection is wrapped in TLS so I cannot see the CredSSP headers being exchanged. But the event log error does indicate what the problem is, the CredSSP client is sending a TLS 1.2 protocol handshake but there were no common cipher suites between the client and the server so the server rejected the handshake. The error 

> A fatal alert was generated and sent to the remote endpoint. This may result in termination of the connection. The TLS protocol defined fatal error code is 40. The Windows SChannel error state is 1205.
Event Xml:

The TLS error code 40 means `SSL3_ALERT_HANDSHAKE_FAILURE` telling you the failure happened during the TLS handshake where the client and server negotiate a common protocol and cipher suite to use. The Schannel error state 1205 means that there was no common cipher suite between the 2. I do find it curious that you can use CURL to connect to the endpoint but that could be explained by CURL using a different OpenSSL backend.

Could you set `ansible_port: 5985` and do a capture over that port and share that here. When using http I can see the actual CredSSP tokens and then decode the handshake values that are exchanged between the client and server to figure out what the client may be offering differently.

**Comment by sf32738** [comment] 2020-08-05 19:53
Sorry about that --- I did intent to do it via non-ssl and forgot about it.   Attached is the non-SSL connection.
[credssp_error_nonSSL.zip](https://github.com/jborean93/requests-credssp/files/5030880/credssp_error_nonSSL.zip)

**Comment by sf32738** [comment] 2020-08-05 20:02
Here is the view from the Windows Server 2012R2 side of the connection.
[credssp_win2012R2_server.zip](https://github.com/jborean93/requests-credssp/files/5030914/credssp_win2012R2_server.zip)

**Comment by jborean93** [comment] 2020-08-05 22:39
Ok this is interesting, your HTTPS capture showed that the HTTP connection negotiated natively in Python supported 43 cipher suites with the higher priority ones being

![image](https://user-images.githubusercontent.com/8462645/89469351-97461f00-d7bc-11ea-8ecc-dbe25f741162.png)

The response from the sever selected `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)` which is a few entries down the list but considering the age of Server 2012 R2 it makes sense that it doesn't support some of the newer cipher suites like the GCM variants.

When we look at the client hello generated for CredSSP we can see that it supports even more cipher suites as well as one we know that the server already supports based on a successful TLS exchange from above.

![image](https://user-images.githubusercontent.com/8462645/89469858-b5f8e580-d7bd-11ea-8103-bd2d7714d5aa.png)

This doesn't make any sense to me as the error from SChannel indicates there wasn't a common cipher suite but we know an existing one that the client (CredSSP) is offering was successful before.

Can you use CredSSP from an actual Windows host to that Server 2012 host successfully? Will be interesting to see if Windows is able to auth as CredSSP against a host that requests-credssp doesn't work on.

Another thing you can look into is to enable the SChannel event logs, I think they are set to just log error messages but you might get some more info by logging everything. To enable these logs go to `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurityProviders\SCHANNEL` and set `EventLogging` to `7` as per [this guide](https://support.microsoft.com/en-us/help/260729/how-to-enable-schannel-event-logging-in-windows-and-windows-server). After you reboot try and connect again from Ansible and see if there is any more information as to why it failed fin the `System` event log.

**Comment by sf32738** [comment] 2020-08-06 00:25
Give me a bit to perform the further diag.  I may not be able to get to it this evening, but will for sure tomorrow morning.
Thank you for your time on this troubleshooting.  This is a great help so far.

**Comment by sf32738** [comment] 2020-08-06 12:09
Well --- here is a kicker for you.    

Did an identical test from my Ubuntu 18.04.x host and it works flawless.

```
$ ansible -i inventory/devops -m setup devops-winsvr2012-01 -vvvv
ansible 2.9.9
  config file = /home/atladmin/.ansible.cfg
  configured module search path = [u'/home/atladmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
Using /home/atladmin/.ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/atladmin/inventory/devops as it did not pass its verify_file() method
script declined parsing /home/atladmin/inventory/devops as it did not pass its verify_file() method
auto declined parsing /home/atladmin/inventory/devops as it did not pass its verify_file() method
Parsed /home/atladmin/inventory/devops inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/minimal.pyc
META: ran handlers
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/setup.ps1
Pipelining is enabled.
<10.10.190.109> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5985 TO 10.10.190.109
EXEC (via pipeline wrapper)

devops-winsvr2012-01 | SUCCESS => {
```

```
$ pip list | egrep "winrm|credssp"
pywinrm                            0.4.1          
requests-credssp                   1.1.0          
```

```
$ python --version
Python 2.7.17
```

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

----

I did enable the extended event logging on the Windows server --- It provided no additional logs other than the two errors that I already posted.  

When I ran the test from my Ubuntu 18 server, it did provide an additional log entry for SCHANNEL.

```
Creating an SSL client credential.

An SSL server handshake completed successfully. The negotiated cryptographic parameters are as follows.

   Protocol: TLS 1.2
   CipherSuite: 0xC028
   Exchange strength: 521
```

PCAP of successful connectivity and data.
[ubuntu18_winsvr2012r2.zip](https://github.com/jborean93/requests-credssp/files/5034690/ubuntu18_winsvr2012r2.zip)

**Comment by sf32738** [comment] 2020-08-06 12:24
I noticed the versions were different on the requests-credssp, so for sake of argument, I upgraded the Ubuntu 18.x server to match the same version (1.1.1)

```
$ pip list | egrep "winrm|credssp"
pywinrm                            0.4.1          
requests-credssp                   1.1.1   
```

Still a successful connection.
```
$ ansible -i inventory/devops -m setup devops-winsvr2012-01 -vvvv
ansible 2.9.9
  config file = /home/ansible/.ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
Using /home/ansible/.ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/ansible/inventory/devops as it did not pass its verify_file() method
script declined parsing /home/ansible/inventory/devops as it did not pass its verify_file() method
auto declined parsing /home/ansible/inventory/devops as it did not pass its verify_file() method
Parsed /home/ansible/inventory/devops inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/minimal.pyc
META: ran handlers
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/setup.ps1
Pipelining is enabled.
<10.10.190.109> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5985 TO 10.10.190.109
EXEC (via pipeline wrapper)
devops-winsvr2012-01 | SUCCESS => {
```

**Comment by sf32738** [comment] 2020-08-06 12:28
Updated my Ubuntu 18.x server to Ansible 2.9.11 to rule that out as well.

```
$ ansible -i inventory/devops -m setup devops-winsvr2012-01 -vvvv
ansible 2.9.11
  config file = /home/ansible/.ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
Using /home/ansible/.ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/ansible/inventory/devops as it did not pass its verify_file() method
script declined parsing /home/ansible/inventory/devops as it did not pass its verify_file() method
auto declined parsing /home/ansible/inventory/devops as it did not pass its verify_file() method
Parsed /home/ansible/inventory/devops inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/minimal.pyc
META: ran handlers
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/setup.ps1
Pipelining is enabled.
<10.10.190.109> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5985 TO 10.10.190.109
EXEC (via pipeline wrapper)
devops-winsvr2012-01 | SUCCESS => {
```

**Comment by jborean93** [comment] 2020-08-07 02:06
I'm just about to look into the exchange for the successful connection to find any differences, thanks for those details. I don't think it's the version with requests-credssp or ansible that's at fault here but something either with OpenSSL or pyOpenSSL that's in use. This library uses pyOpenSSL to manage the TLS connection for CredSSP which in turn uses OpenSSL. It could be a difference between the 2 OpenSSL versions (or at least what pyOpenSSL is using) that is the culprit but that's a shot in the dark.

Could you compare the output of `$(head -n1 $(which ansible) | awk '{print substr($0, 3)}') -m OpenSSL.debug` against both hosts?

**Comment by sf32738** [comment] 2020-08-07 02:22
Ubuntu 18.x
```
# $(head -n1 $(which ansible) | awk '{print substr($0, 3)}') -m OpenSSL.debug
pyOpenSSL: 19.1.0
cryptography: 2.1.4
cffi: 1.14.0
cryptography's compiled against OpenSSL: OpenSSL 1.1.1  11 Sep 2018
cryptography's linked OpenSSL: OpenSSL 1.1.1  11 Sep 2018
Pythons's OpenSSL: OpenSSL 1.1.1  11 Sep 2018
Python executable: /usr/bin/python2
Python version: 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0]
Platform: linux2
sys.path: ['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/atladmin/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
```


Ubuntu 20.x
_Note: Ansible had to be installed via PIP3 as there was no PPA available (that I could find) for current release (2.9.11)_

```
# $(head -n1 $(which ansible) | awk '{print substr($0, 3)}') -m OpenSSL.debug
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/OpenSSL/debug.py", line 7, in <module>
    import cffi
ModuleNotFoundError: No module named 'cffi'
```
```
# apt info ansible
Package: ansible
Version: 2.9.6+dfsg-1
Priority: optional
Section: universe/admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
```

**Comment by sf32738** [comment] 2020-08-07 02:35
Ok, so to continue the 'make it match' theory --- I installed CFFI for pip3 on the Ubuntu 20.x host and retested the Windows Server 2012R2 connection.  --- Failed

```
$ ansible -m setup -i inventory/devops devops-winsvr2012-01
devops-winsvr2012-01 | UNREACHABLE! => {
    "changed": false,
    "msg": "credssp: Server did not response with a CredSSP token after step Step 1. TLS Handshake - actual 'Negotiate, CredSSP'",
    "unreachable": true
}
```

But --- I now have the output for Ubuntu 20.x that you wanted.   So there is that ...

```
$ $(head -n1 $(which ansible) | awk '{print substr($0, 3)}') -m OpenSSL.debug
pyOpenSSL: 19.0.0
cryptography: 2.8
cffi: 1.14.1
cryptography's compiled against OpenSSL: OpenSSL 1.1.1d  10 Sep 2019
cryptography's linked OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
Pythons's OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
Python executable: /usr/bin/python3
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]
Platform: linux
sys.path: ['/home/ansible', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/ansible/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
```

**Comment by sf32738** [comment] 2020-08-07 02:38
Upgraded pyOpenSSL package to match (v19.1.0)

```
$ pip3 install pyOpenSSL==19.1.0
Collecting pyOpenSSL==19.1.0
  Downloading pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 2.0 MB/s 
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from pyOpenSSL==19.1.0) (1.14.0)
Requirement already satisfied: cryptography>=2.8 in /usr/lib/python3/dist-packages (from pyOpenSSL==19.1.0) (2.8)
ERROR: winrmlib 1.3 has requirement requests==2.5.0, but you'll have requests 2.24.0 which is incompatible.
Installing collected packages: pyOpenSSL
Successfully installed pyOpenSSL-19.1.0
```

```
$ $(head -n1 $(which ansible) | awk '{print substr($0, 3)}') -m OpenSSL.debug
pyOpenSSL: 19.1.0
cryptography: 2.8
cffi: 1.14.1
cryptography's compiled against OpenSSL: OpenSSL 1.1.1d  10 Sep 2019
cryptography's linked OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
Pythons's OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
Python executable: /usr/bin/python3
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]
Platform: linux
sys.path: ['/home/ansible', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/ansible/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
```

```
$ ansible -m setup -i inventory/devops devops-winsvr2012-01
devops-winsvr2012-01 | UNREACHABLE! => {
    "changed": false,
    "msg": "credssp: Server did not response with a CredSSP token after step Step 1. TLS Handshake - actual 'Negotiate, CredSSP'",
    "unreachable": true
}
```

**Comment by jborean93** [comment] 2020-08-07 05:58
You aren't making this easy for me :P

Here's a comparison between the Client Hello packets send by Ubuntu 20.04 (left) and Ubuntu 18.04 (right)

![image](https://user-images.githubusercontent.com/8462645/89607602-40bd0b80-d8b6-11ea-9666-f39dc19e016a.png)

The only difference between the 2 that I can find (apart from Random) is that Ubuntu 18.04 offers 3 more signature algorithms than 20.04

* `ecdsa_sha1 (0x0203)`
* `rsa_pkcs1_sha1 (0x0201)`
* `SHA1 DSA (0x0202)`

When we look at the Server Hello packet that was returned to Ubuntu 18.04 we can see that it chose `rsa_pkcs1_sha1 (0x0201)`.

![image](https://user-images.githubusercontent.com/8462645/89608041-541ca680-d8b7-11ea-9acc-e98761870e28.png)

This is not a concept I'm too familiar with so I'm getting all this info from the TLS 1.2 [RFC 5246 7.4.1.4.1](https://tools.ietf.org/html/rfc5246#section-7.4.1.4.1) where it states

>   The client uses the "signature_algorithms" extension to indicate to the server which signature/hash algorithm pairs may be used in digital signatures.

Further down it states in the Server Hello [7.4.2. Server Certificate](https://tools.ietf.org/html/rfc5246#section-7.4.2) section states that

> If the client provided a "signature_algorithms" extension, then all certificates provided by the server MUST be signed by a hash/signature algorithm pair that appears in that extension

It doesn't necessarily state that the selected signature algorithm by the server must match the one that the cert uses but somewhat indicates that the client must at least offer it in it's list.

This is coming to guess work here but here is what I think is happening

* The OpenSSL install on Ubuntu 20.04 that cryptography is linked to is set to not support RSA SHA1 signature algorithm
* OpenSSL on Ubuntu 18.04 does because it's based on a different build/version of OpenSSL
* Server 2016+ will generate an ephemeral cert with a stronger signature algorithm or at least select a stronger signature algorithm
    * I tested against 2019 and I can confirm that it selected `rsa_pkcs1_sha256`

As I was typing all this I was finally able to replicate this in a Docker container. Ultimately the problem stems from the `python3-cryptography` package that comes in Ubuntu 20.04. This package would be linked to a specific build of OpenSSL which I guess is configured with a subset of signature algorithms that it supports.

There are 3 options I can see you continue forward with

* Pursue this further with the Ubuntu package maintainer for `python3-openssl` and see if they can explain this further/re-add sha1 rsa signature algorithms upport
    * I doubt this would lead anywhere, I'm not even sure if it was a decision made on purpose or just a byproduct of something else
    * I have no control over this package so I don't know where to start
* Remove the package with `apt remove python3-cryptography` and install it from pip with `pip3 install cryptography`
    * Based on my testing the version here is linked with a known working version of OpenSSL
    * You probably will get a newer version of the package as well
    * This is probably what I would do myself
* From my tests if you set CredSSP to use a specific cert then it may control the signature algorithm behaviour on the server allowing the Ubuntu package of cryptography to work

For this last option, you can use the same certificate that your HTTPS WinRM endpoint uses if you wish

```powershell
$thumbprint = Get-Item WSMan:\localhost\Listener\* |
    Where-Object { 'Transport=HTTPS' -in $_.Keys } |
    Get-ChildItem |
    Where-Object Name -eq CertificateThumbprint |
    Select-Object -ExpandProperty Value
Set-Item -LiteralPath WSMan:\localhost\Service\CertificateThumbprint -Value $thumbprint
Restart-Service -Name WinRM
```

The only extra requirement is to make sure `Network Service` can access the public key for this cert. You can configure this in `certlm.exe`, find the cert, right click cert -> All Tasks -> Manage Private Keys -> Add `NETWORK SERVICE` Full control permissions. This would have to be done on every 2012 R2 host you have so it's probably not viable if you have multiple hosts you need to connect to.

**Comment by sf32738** [comment] 2020-08-07 10:51
Very nice depth of explanation sir.  This helps shine a light on the root cause.

For other reviewing this incident, here are the steps taken to get this working on a Ubuntu 20.x / Ansible 2.9.11 environment.

```
sudo apt remove -y python3-cryptography;
sudo pip3 install cryptography;
```

Validation of connectivity:
```
$ ansible -m setup -i inventory/devops devops-winsvr2012-01
devops-winsvr2012-01 | SUCCESS => {
```

Thank you very much Jordan for working through this with me.

**Closed** 2020-08-07 11:05 UTC

**Comment by jborean93** [comment] 2020-08-07 22:35
Glad it's all working for you now.

**Comment by brianeray** [comment] 2022-05-20 15:14
I know this is closed but it has helped me so much, first with Ubuntu 20.04 and again just yesterday after upgrading to 22.04. Here are some combinations of `cryptography` and `requests-credssp` that I tried against some of our Win Server 2012 and 2016 hosts. This may help others who come across this issue.

```
  cryptography  requests-credssp  Works vs 2k12?  vs 2k16?
  ------------  ----------------  --------------  --------
        36.0.1             1.3.1             yes       yes
        36.0.2             1.3.1             yes       yes
        36.0.2             2.0.0              no       yes
        37.0.0             1.3.1              no        no
        37.0.0             2.0.0              no       yes
        37.0.1             2.0.0              no       yes
        37.0.2             2.0.0              no       yes
```

**Comment by dbarrachina-ntt** [comment] 2022-12-21 15:46
Not ideal as you are allowing weak cyphers but changing openssl config from DEFAULT:@SECLEVEL=2 to DEFAULT:@SECLEVEL=1 did the trick to me.

That's explained in one of the solutions here: https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level

More info on the levels here: https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html
